# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation yaml: !include_dir_merge_list automations/
automation: !include automations.yaml

script: !include_dir_merge_named scripts/
scene: !include scenes.yaml

lovelace:
  resource_mode: yaml
  resources:
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/decluttering-card/decluttering-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
  dashboards:
    lovelace-home:
      mode: yaml
      filename: dashboards/home/home.yaml
      title: Home
      icon: mdi:home-assistant
      show_in_sidebar: true
    lovelace-laundry:
      mode: yaml
      filename: dashboards/laundry/laundry.yaml
      title: Laundry
      icon: mdi:washing-machine
      show_in_sidebar: true
    lovelace-climate:
      mode: yaml
      filename: dashboards/climate/climate.yaml
      title: Climate
      icon: mdi:thermometer
      show_in_sidebar: true
    lovelace-lights:
      mode: yaml
      filename: dashboards/lights/lights.yaml
      title: Lights
      icon: mdi:lightbulb-group
      show_in_sidebar: true
